---
name: ci

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: configure cmake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
      - name: build
        working-directory: build
        run: make -j 
      - name: Upload static lib
        uses: actions/upload-artifact@v2
        with:
          name: libmerase-static.a
          path: ${{github.workspace}}/build/*.a